import React from 'react';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.css';
import { AuthProvider } from "@/app/context/auth";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}